// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATC9z1vnFqURU9g91W2H3ByxgvYfXBYkI',
    appId: '1:50293370395:web:73a1f05921a433169112be',
    messagingSenderId: '50293370395',
    projectId: 'tripmate-17971',
    authDomain: 'tripmate-17971.firebaseapp.com',
    storageBucket: 'tripmate-17971.firebasestorage.app',
    measurementId: 'G-JW42JMQBB2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApDGGSlUN1zlA1liBZuFuOrUrD8yMkN8s',
    appId: '1:50293370395:android:1bdb3f409d93323c9112be',
    messagingSenderId: '50293370395',
    projectId: 'tripmate-17971',
    storageBucket: 'tripmate-17971.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAV-gywIkfFgInrsdvkR_sMmryAXhh40-M',
    appId: '1:50293370395:ios:5d6ba00e56b797909112be',
    messagingSenderId: '50293370395',
    projectId: 'tripmate-17971',
    storageBucket: 'tripmate-17971.firebasestorage.app',
    iosBundleId: 'com.example.tripmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAV-gywIkfFgInrsdvkR_sMmryAXhh40-M',
    appId: '1:50293370395:ios:5d6ba00e56b797909112be',
    messagingSenderId: '50293370395',
    projectId: 'tripmate-17971',
    storageBucket: 'tripmate-17971.firebasestorage.app',
    iosBundleId: 'com.example.tripmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATC9z1vnFqURU9g91W2H3ByxgvYfXBYkI',
    appId: '1:50293370395:web:40aba4785bed33d99112be',
    messagingSenderId: '50293370395',
    projectId: 'tripmate-17971',
    authDomain: 'tripmate-17971.firebaseapp.com',
    storageBucket: 'tripmate-17971.firebasestorage.app',
    measurementId: 'G-LCN60B6LZ4',
  );
}
